print("Mencari Nilai X1,X2,X3 dengan Metode Eliminasi Gauss")
print("Input Matriks")
a=int(input("nilai A = "))
b=int(input("nilai B = "))
c=int(input("nilai C = "))
d=int(input("nilai D = "))
e=int(input("nilai E = "))
f=int(input("nilai F = "))
g=int(input("nilai G = "))
h=int(input("nilai H = "))
i=int(input("nilai I = "))
#Mencari Nilai X1, X2, X3
print("Mencari Nilai X1, X2, X3")
print("Nilai b")
b1=int(input("nilai B1 = "))
b2=int(input("nilai B2 = "))
b3=int(input("nilai B3 = "))
#Eliminasi gauss
print("Mencari Eliminasi Gaus")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B1=b1+b2
a=(a+d)
b=(b+e)
c=(c+f)
b1=(b1+b2)
#Langka 1
print("Langka 1 buat B1=b1+b2")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B2=b2+b1
d=(d+a)
e=(e+b)
f=(f+c)
b2=(b2+b1)
#Langka 2
print("Langka 2 buat B2=b2+b1")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B3=b3-2.b1
g=(g-(2*a))
h=(h-(2*b))
i=(i-(2*c))
b3=(b3-(2*b1))
#Langka 3
print("Langka 3 buat B3= b3-2.b1")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")

#Untuk Nilai B2=b2/10
d=(d/10)
e=(e/10)
f=(f/10)
b2=(b2/10)
#Langka 4
print("Langka 4 buat B2= b2/10")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B3=b3+17*b2
g=(g+(17*d))
h=(h+(17*e))
i=(i+(17*f))
b3=(b3+(17*b2))
#Langka 5
print("Langka 5 buat B3= b3+17.b2")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B3=b3/1.9
g=(g/1.9)
h=(h/1.9)
i=(i/1.9)
b3=(b3/1.9)
#Langka 6
print("Langka 6 buat B3= b3/1.9")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')

print("---------------------------")
#Untuk Nilai B2=b2+(b3*0,3)
d=(d+(g*0.3))
e=(e+(h*0.3))
f=(f+(i*0.3))
b2=(b2+(b3*0.3))
#Langka 7
print("Langka 7 B2=b2+(b3*0,3)")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B1=-7*b2+b1
a=((-7*d)+a)
b=((-7*e)+b)
c=((-7*f)+c)
b1=((-7*b2)+b1)
#Langka 8
print("Langka 8 buat B1=b1-1.1*b3")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')
print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Untuk Nilai B1=b3+b1
a=(g+a)
b=(h+b)
c=(i+c)
b1=(b3+b1)
#Langka 9
print("Langka 9 buat B2=b2+0.3*b3")
print('B1=│',a,',b,',c,'│',b1,'│')
print('B2=│',d,',e,',f,'│',b2,'│')

print('B3=│',g,',h,',i,'│',b3,'│')
print("---------------------------")
#Mencari nilai X1, X2, X3
print("Nilai x1,x2,x3 Menggunakan Eliminasi Gauss")
print("Nilai x1,x2,x3 di dapat hasil Eliminasi Gauss Jordan")
x1=round(b1)
print("x1=",x1," ")
x2=round(b2)
print("x2=",x2," ")
x3=round(b3)
print("x3=",x3," ")
print("---------------------------")